version: 2.1
orbs:
  docker: circleci/docker@1.4.0
  heroku: circleci/heroku@1.2.2
workflows:
  code_analysis-build-push-docker-heroku:
    jobs:
      - code-analysis:
          context: SonarCloud
      - docker/hadolint:
          dockerfiles: Dockerfile.web
          requires:
            - code-analysis
      - docker/publish:
          dockerfile: Dockerfile.web
          image: victorgrubio/ecommerce-backend-spring
          tag: 'latest,1.0.0'
          requires:
            - docker/hadolint
      - heroku-docker-deploy:
          requires:
            - docker/publish
jobs:
  code-analysis:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.login=$SONAR_TOKEN
  heroku-docker-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - heroku/install
      - heroku/check-authentication
      - setup_remote_docker
      - checkout
      - heroku/push-docker-image:
          app-name: $HEROKU_APP_NAME
          recursive: true
      - heroku/release-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: web